- name: copy rabbitmq repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo


- name: install rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: latest

- name: start rabbitmq service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: create app user
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:username token={{ token }} url=http://vault-int.prashumps.online:8200') }}"
    password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:password token={{ token }} url=http://vault-int.prashumps.online:8200') }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present


