- name: install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: setup mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass Roboshop@1


