- name: install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: setup mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:password token={{ token }} url=http://vault-int.prashumps.online:8200') }}


