- name: install python
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel

- name: load app pre-requisite
  ansible.builtin.include_tasks:
    file: app_pre_setup.yml

- name: download dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app
